### ISSUE TITLE
No package found for 'chef-server' with version 'latest' for current platform in 'stable' channel.

### ISSUE THREAD

**Issue by petetnt** [chef-cookbooks/chef-server#124]
### Cookbook version

v5.0.1
### Chef-client version

12.12.15
### Platform Details

Vagrant / bento/ubuntu-16.04
### Scenario:

Trying to run the `default` recipe
### Steps to Reproduce:
1. Try to provision the following 

```
Vagrant.configure("2") do |config|
  config.omnibus.chef_version = '12.12.15'

  config.vm.define "chef_server" do |chef_server|
    chef_server.vm.box = "bento/ubuntu-16.04"    
    chef_server.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "vendor/cookbooks"
      chef.add_recipe "chef-server::default"
    end
  end
end
```
### Expected Result:

The machine successfully goes up
### Actual Result:

`chef-ingredient` fails to find a package for `chef-server`.

```
==> chef_server: RuntimeError
==> chef_server:
==> chef_server: ------------
==> chef_server:
==> chef_server: No package found for 'chef-server' with version 'latest' for current platform in 'stable' channel.
==> chef_server:
==> chef_server:     Check that the package exists.
==> chef_server:
==> chef_server:     Cookbook Trace:
==> chef_server:     ---------------
==> chef_server:     /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:95:in `configure_from_channel'
==> chef_server:     /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:46:in `configure_package'
==> chef_server:     /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
==> chef_server:     /var/chef/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
==> chef_server:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
==> chef_server:
==> chef_server:     Resource Declaration:
==> chef_server:     ---------------------
==> chef_server:     # In /var/chef/cache/cookbooks/chef-server/recipes/default.rb
==> chef_server:
==> chef_server:      29: chef_ingredient 'chef-server' do
==> chef_server:      30:   extend ChefServerCookbook::Helpers
==> chef_server:      31:   version node['chef-server']['version'] unless node['chef-server']['version'].nil?
==> chef_server:      32:   package_source node['chef-server']['package_source']
==> chef_server:      33:   config <<-EOS
==> chef_server:      34: topology "#{node['chef-server']['topology']}"
==> chef_server:      35: #{"api_fqdn \"#{node['chef-server']['api_fqdn']}\"" if api_fqdn_available?}
==> chef_server:      36: #{node['chef-server']['configuration']}
==> chef_server:      37: EOS
==> chef_server:      38:   action :install
==> chef_server:      39: end
==> chef_server:      40:
==> chef_server:
==> chef_server:     Compiled Resource:
==> chef_server:     ------------------
==> chef_server:     # Declared in /var/chef/cache/cookbooks/chef-server/recipes/default.rb:29:in `from_file'
==> chef_server:
==> chef_server:     chef_ingredient("chef-server") do
==> chef_server:       action [:install]
==> chef_server:       retries 0
==> chef_server:       retry_delay 2
==> chef_server:       default_guard_interpreter :default
==> chef_server:       declared_type :chef_ingredient
==> chef_server:       cookbook_name "chef-server"
==> chef_server:       recipe_name "default"
==> chef_server:       config "topology \"standalone\"\napi_fqdn \"vagrant.vm\"\n\n"
==> chef_server:       product_name "chef-server"
==> chef_server:     end
==> chef_server:
==> chef_server:     Platform:
==> chef_server:     ---------
==> chef_server:     x86_64-linux
```

**Comment by petetnt** [comment]
Doh, it says on the README.md that this cookbook hasn't been tested on 16.04. yet and truly the `chef-server` package isn't on the Ubuntu 16.04 branch yet: https://packages.chef.io/stable/ubuntu/16.04/

I guess the options here are either resolving to the 14.04 repo or downgrading the box?

**Comment by cheeseplus** [comment]
16.04 is now supported - closing.
