### ISSUE TITLE
sync addon not found

### ISSUE THREAD

**Issue by akadoya** [chef-cookbooks/chef-server#131]
### Cookbook version
5.0.1

### Chef-client version
12.8.1

chef server version is 12.5.0

### Platform Details
Ubuntu 14.04

### Scenario:
I have something like below in our wrapper cookbook and it was working just fine with chef-ingredient 0.19.0.
```
node.default['chef-server']['addons'] = [
    "sync",
    "push-jobs-server",
    "manage",
    "reporting"]
include_recipe 'chef-server::addons'
```

However, other cookbooks that installs `push-jobs-client` by `include_recipe 'push-jobs::default'` started failing with 404 exceptions and I had to upgrade chef-ingredient's dependency to the latest(0.21.2) to fix this issue.

And now, chef-server's sync addon is not found through this cookbook with using v0.21.2 chef-ingredient.

### Expected Result:
Successfully install chef-sync addon

### Actual Result:
```
           RuntimeError
           ------------
           No package found for 'sync' with version 'latest' for current platform in 'stable' channel.
           Check that the package exists.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:96:in `configure_from_channel'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:46:in `configure_package'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/chef-server/recipes/addons.rb

            20:   chef_ingredient addon do
            21:     accept_license node['chef-server']['accept_license'] unless node['chef-server']['accept_license'].nil?
            22:     notifies :reconfigure, "chef_ingredient[#{addon}]"
            23:   end
            24: end
```

**Comment by cheeseplus** [comment]
chef-sync is deprecated and as such if you are a current customer with license you should contact your CSE regarding a package.
