### ISSUE TITLE
Addon installs fail

### ISSUE THREAD

**Issue by predominant** [chef-cookbooks/chef-server#142]
### Cookbook version
5.4.0

### Chef-client version
13.2.20

### Platform Details
Ubuntu 14.04

### Scenario:
```
kitchen converge add-ons-no-fqdn-ubuntu-1404
```

### Steps to Reproduce:
```
kitchen converge add-ons-no-fqdn-ubuntu-1404
```

### Expected Result:
Clean chef converge with addons installed

### Actual Result:
Error, see below.

```
$ kitchen converge add-ons-no-fqdn-ubuntu-1404
-----> Starting Kitchen (v1.16.0)
-----> Creating <add-ons-no-fqdn-ubuntu-1404>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
       ==> default: A newer version of the box 'bento/ubuntu-14.04' is available! You currently
       ==> default: have version '2.3.1'. The latest is version '2.3.7'. Run
       ==> default: `vagrant box update` to update.
       ==> default: Setting the name of the VM: kitchen-chef-server-add-ons-no-fqdn-ubuntu-1404_default_1501776626428_6461
       ==> default: Fixed port collision for 22 => 2222. Now on port 2200.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
           default: Adapter 2: hostonly
       ==> default: Forwarding ports...
           default: 22 (guest) => 2200 (host) (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2200
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Configuring and enabling network interfaces...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => /Users/graham.weldon/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <add-ons-no-fqdn-ubuntu-1404> created.
       Finished creating <add-ons-no-fqdn-ubuntu-1404> (0m51.69s).
-----> Converging <add-ons-no-fqdn-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 14.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.1635/metadata.txt
       trying wget...
       sha1	2952362ec5d44ec776ace492c29a36c423437f39
       sha256	88cd274a694bfe23d255937794744d50af972097958fa681a544479e2bfb7f6b
       url	https://packages.chef.io/files/stable/chef/13.2.20/ubuntu/14.04/chef_13.2.20-1_amd64.deb
       version	13.2.20
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef_13.2.20-1_amd64.deb already exists, verifiying checksum...
       Comparing checksum with sha256sum...
       checksum compare succeeded, using existing file!
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       Installing chef 
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 35284 files and directories currently installed.)
       Preparing to unpack .../cache/chef_13.2.20-1_amd64.deb ...
       Unpacking chef (13.2.20-1) ...
       Setting up chef (13.2.20-1) ...
       Thank you for installing Chef!
       Transferring files to <add-ons-no-fqdn-ubuntu-1404>
       Starting Chef Client, version 13.2.20
       Creating a new client identity for add-ons-no-fqdn-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["test::add-ons-no-fqdn"]
       Synchronizing Cookbooks:
         - test (0.0.1)
         - chef-ingredient (1.1.0)
         - chef-server (5.4.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 6 resources
       Recipe: test::add-ons-no-fqdn
         * apt_update[update] action periodic
           - update new lists of packages
           * directory[/var/lib/apt/periodic] action create (up to date)
           * directory[/etc/apt/apt.conf.d] action create (up to date)
           * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
           * execute[apt-get -q update] action run
             - execute apt-get -q update
         
       Recipe: chef-server::default
         * ruby_block[ensure node can resolve API FQDN] action run (skipped due to only_if)
         * chef_ingredient[chef-server] action install
         Recipe: <Dynamically Defined Resource>
           * chef_gem[mixlib-install] action install
             - install version ~> 2.1 of package mixlib-install
           * ruby_block[stop chef run] action nothing (skipped due to action :nothing)
           * remote_file[/tmp/kitchen/cache/chef-server-core_12.15.8-1_amd64.deb] action create
             - create new file /tmp/kitchen/cache/chef-server-core_12.15.8-1_amd64.deb
             - update content in file /tmp/kitchen/cache/chef-server-core_12.15.8-1_amd64.deb from none to 4351cc
             (file sizes exceed 10000000 bytes, diff output suppressed)
             - change mode from '' to '0644'
           * apt_package[chef-server] action install
             - install version 12.15.8-1 of package chef-server-core
         
       Recipe: chef-server::default
         * file[/tmp/kitchen/cache/chef-server-core.firstrun] action create
           - create new file /tmp/kitchen/cache/chef-server-core.firstrun
         * chef_ingredient_ingredient_config[chef-server] action render
           * directory[/etc/opscode] action create (up to date)
           * file[/etc/opscode/chef-server.rb] action create
             - update content in file /etc/opscode/chef-server.rb from e3b0c4 to 028631
             --- /etc/opscode/chef-server.rb	2017-08-03 16:12:45.990253000 +0000
             +++ /etc/opscode/.chef-chef-server20170803-1725-1d59qm8.rb	2017-08-03 16:12:46.330253000 +0000
             @@ -1 +1,4 @@
             +topology "standalone"
             +
             +
         
         * chef_ingredient[chef-server] action reconfigure
           * chef_ingredient_ingredient_config[chef-server] action render
             * directory[/etc/opscode] action create (up to date)
             * file[/etc/opscode/chef-server.rb] action create (up to date)
       (up to date)
           * execute[chef-server-core-reconfigure] action run
             - execute chef-server-ctl reconfigure
         
       Recipe: chef-server::addons
         * chef_ingredient[manage] action install
           
           ================================================================================
           Error executing action `install` on resource 'chef_ingredient[manage]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `to_sym' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/helpers.rb:41:in `ingredient_package_name'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:54:in `block in configure_from_source_package'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:52:in `configure_from_source_package'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:113:in `configure_from_channel'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:46:in `configure_package'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
           /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/chef-server/recipes/addons.rb
           
            20:   chef_ingredient addon do
            21:     accept_license node['chef-server']['accept_license'] unless node['chef-server']['accept_license'].nil?
            22:     notifies :reconfigure, "chef_ingredient[#{addon}]"
            23:     version ver if defined?(ver)
            24:   end
            25: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/chef-server/recipes/addons.rb:20:in `block in from_file'
           
           chef_ingredient("manage") do
             action [:install]
             default_guard_interpreter :default
             declared_type :chef_ingredient
             cookbook_name "chef-server"
             recipe_name "addons"
             accept_license true
             version nil
           end
           
           System Info:
           ------------
           chef_version=13.2.20
           platform=ubuntu
           platform_version=14.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1720;start=16:11:07;
           executable=/opt/chef/bin/chef-client
           
       
       Running handlers:
       [2017-08-03T16:17:29+00:00] ERROR: Running exception handlers
       [2017-08-03T16:17:29+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-08-03T16:17:29+00:00] ERROR: Exception handlers complete
       [2017-08-03T16:17:29+00:00] ERROR: Exception handlers complete
       Chef Client failed. 11 resources updated in 06 minutes 22 seconds
       [2017-08-03T16:17:29+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-08-03T16:17:29+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-08-03T16:17:29+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-08-03T16:17:29+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-08-03T16:17:29+00:00] ERROR: chef_ingredient[manage] (chef-server::addons line 20) had an error: NoMethodError: undefined method `to_sym' for nil:NilClass
       [2017-08-03T16:17:29+00:00] ERROR: chef_ingredient[manage] (chef-server::addons line 20) had an error: NoMethodError: undefined method `to_sym' for nil:NilClass
       [2017-08-03T16:17:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-08-03T16:17:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <add-ons-no-fqdn-ubuntu-1404>.  Please see .kitchen/logs/add-ons-no-fqdn-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

**Comment by flaccid** [comment]
I am also running into this. Very similar setup:

```
[0m    System Info:[0m
    ------------[0m
    chef_version=13.2.20
[0m    platform=ubuntu
[0m    platform_version=14.04
[0m    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[0m    program_name=chef-solo worker: ppid=10625;start=04:44:50;
[0m    executable=/opt/chef/bin/chef-solo[0m
```

**Comment by flaccid** [comment]
It looks like 5.3.0 might be ok. The format i'm using is array, `"addons":  ["manage","reporting"]`.

Not quite sure why either the node attribute is coming back nil or `addon` in the loop (https://github.com/chef-cookbooks/chef-server/blob/v5.4.0/recipes/addons.rb#L19-L25).

Mine is like:
```
{
  "chef-server": {
    "addons":  ["manage","reporting"]
}
```

**Comment by zl4bv** [comment]
I had some success overcoming this issue by explicitly specifying the versions of the addons to install e.g.

```ruby
{
  "chef-server" => {
    "addons" => {
      "manage" => :latest,
      "reporting" => :latest,
     }
}
```

I think if you don't specify a version it defaults to `nil` in the chef_ingredient resource which then gets passed to [this method](https://github.com/chef/mixlib-install/blob/v2.1.12/lib/mixlib/install/product.rb#L156) as the second argument, overriding the method default of `:latest`.

**Comment by rreilly-edr** [comment]
I cannot get addons to install, I have tried adding to dna.json, modifying the cookbook attributes directly. I am as my runlist and command
sudo chef-solo -o 'recipe[chef-server::default],recipe[chef-server::addons]'

**Comment by tas50** [comment]
5.5.1 should resolve this failure by properly checking to see if the version is nil before we specify that nil value.
