### ISSUE TITLE
Chef-server installation using Chef-solo & Ubuntu 18.04

### ISSUE THREAD

**Issue by idistech** [chef-cookbooks/chef-server#155]
### Cookbook version
5.5.1

### Chef-client version
14.2.0

### Platform Details
Ubuntu 18_04

### Scenario:
Install Chef-server using chef-solo

### Steps to Reproduce:
sudo chef-solo -c solo.rb  -o 'recipe[chef-server::default]'

### Expected Result:
Fails to run 

### Actual Result:

`2018-07-21T16:06:16+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /home/ubuntu/chef-repo, /home/ubuntu/chef-repo
  One version per cookbook

Starting Chef Client, version 14.2.0
[2018-07-21T16:06:16+00:00] INFO: *** Chef 14.2.0 ***
[2018-07-21T16:06:16+00:00] INFO: Platform: x86_64-linux
[2018-07-21T16:06:16+00:00] INFO: Chef-client pid: 11469
[2018-07-21T16:06:16+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-07-21T16:06:18+00:00] WARN: Run List override has been provided.
[2018-07-21T16:06:18+00:00] WARN: Original Run List: []
[2018-07-21T16:06:18+00:00] WARN: Overridden Run List: [recipe[chef-server::default]]
[2018-07-21T16:06:18+00:00] INFO: Run List is [recipe[chef-server::default]]
[2018-07-21T16:06:18+00:00] INFO: Run List expands to [chef-server::default]
[2018-07-21T16:06:18+00:00] INFO: Starting Chef Run for build01.cloud-dog.com
[2018-07-21T16:06:18+00:00] INFO: Running start handlers
[2018-07-21T16:06:18+00:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef-server::default"]
[2018-07-21T16:06:18+00:00] INFO: Loading cookbooks [chef-server@5.5.1, chef-ingredient@2.3.2]
[2018-07-21T16:06:18+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - chef-server (5.5.1)
  - chef-ingredient (2.3.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 4 resources
Recipe: chef-server::default
  * ruby_block[ensure node can resolve API FQDN] action run (skipped due to not_if)
  * chef_ingredient[chef-server] action install
  Recipe: <Dynamically Defined Resource>
    * chef_gem[mixlib-install] action install (up to date)
    
    ================================================================================
    Error executing action `install` on resource 'chef_ingredient[chef-server]'
    ================================================================================
    
    Mixlib::Install::Backend::ArtifactsNotFound
    -------------------------------------------
    No artifacts found matching criteria.
      product name: chef-server
      channel: stable
      version: latest
      platform: ubuntu
      platform version: 18.04
      architecture: x86_64
      compatibility mode: false
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:100:in `configure_from_channel'
    /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:49:in `configure_package'
    /var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb:23:in `handle_install'
    /var/chef/cache/cookbooks/chef-ingredient/resources/chef_ingredient.rb:57:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef-server/recipes/default.rb
    
     29: chef_ingredient 'chef-server' do
     30:   extend ChefServerCookbook::Helpers
     31:   version node['chef-server']['version'] unless node['chef-server']['version'].nil?
     32:   package_source node['chef-server']['package_source']
     33:   config <<-EOS
     34: topology "#{node['chef-server']['topology']}"
     35: #{"api_fqdn \"#{node['chef-server']['api_fqdn']}\"" if api_fqdn_available?}
     36: #{node['chef-server']['configuration']}
     37: EOS
     38:   action :install
     39: end
     40: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef-server/recipes/default.rb:29:in `from_file'
    
    chef_ingredient("chef-server") do
      action [:install]
      default_guard_interpreter :default
      declared_type :chef_ingredient
      cookbook_name "chef-server"
      recipe_name "default"
      package_source nil
      config "topology \"standalone\"\napi_fqdn \"build01.cloud-dog.com\"\n\n"
      product_name "chef-server"
      platform "ubuntu"
      platform_version "18.04"
      architecture "x86_64"
    end
    
    System Info:
    ------------
    chef_version=14.2.0
    platform=ubuntu
    platform_version=18.04
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/usr/bin/chef-solo
    executable=/opt/chefdk/bin/chef-solo
    
[2018-07-21T16:06:19+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2018-07-21T16:06:19+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-07-21T16:06:19+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2018-07-21T16:06:19+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-21T16:06:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-21T16:06:19+00:00] FATAL: Mixlib::Install::Backend::ArtifactsNotFound: chef_ingredient[chef-server] (chef-server::default line 29) had an error: Mixlib::Install::Backend::ArtifactsNotFound: No artifacts found matching criteria.
  product name: chef-server
  channel: stable
  version: latest
  platform: ubuntu
  platform version: 18.04
  architecture: x86_64
  compatibility mode: false

`

Not support yet ?
Thanks for your assistance

**Comment by joe4dev** [comment]
Same issue here, reverted back to `Ubuntu 16.04` for now

**Comment by idistech** [comment]
Ditto, 
Had a poke around chef-ingredients cookbook, but wasnt obvious what needed to be done. Happy to help test once its ready .
Best
